# Makefile for .NET Core project

# Default target executed when no arguments are given to make.
default: run

# Target to run the project
run:
	dotnet run

# Target to clean the project
clean:
	rm -rf bin
	rm -rf obj
	rm -rf logs

.PHONY: default run clean